export const types = Object.freeze({
	USERS_FILL: 'USERS_FILL',
	USERS_START_FETCHING: 'USERS_START_FETCHING',
	USERS_STOP_FETCHING: 'USERS_STOP_FETCHING',
	USERS_SET_FETCHING_ERROR: 'USERS_SET_FETCHING_ERROR',

	USERS_FETCH_ASYNC: 'USERS_FETCH_ASYNC',
	USERS_CREATE_ASYNC: 'USERS_CREATE_ASYNC',
	USERS_EDIT_ASYNC: 'USERS_EDIT_ASYNC',
	USERS_REMOVE_ASYNC: 'USERS_REMOVE_ASYNC',
	USERS_UPDATE_ASYNC: 'USERS_UPDATE_ASYNC'
});
